### ISSUE TITLE
Specular reflection and Phong shading

### ISSUE THREAD

**Issue by RichardMulder** [ggambetta/computer-graphics-from-scratch#17]
In both the chapter on specular reflection (Raytracing, Light) and Phong shading (Rasterization, Shading), you apply the specular intensity to the _object_ color to get the final color.

However, specular intensity is usually applied to the _light_ color (and lights are usually white, which is why specular highlights are usually white) and added to the diffuse color to get the final color, as quite nicely visually illustrated on the wikipedia page for Phong Shading.

I assume that this might have been a simplification done for educational reasons, but it does mean the shading model you describe in the Phong Shading chapter isn't actually using the Phong reflection model.

I would suggest changing things around to do it the more common way (the changes for the raytracer aren't too bad, but I admit haven't worked through the rasterizer yet), but if you feel this would complicate the code or explanation too much, perhaps just don't call the shading model "Phong".

**Comment by ggambetta** [comment]
Hey Richard, thanks for bringing this up. It definitely looks like an oversight on my part!

However, if I understand correctly, your issue isn't with Phong Shading (interpolated normals, per-pixel lighting calculation), but with the Phong Reflection Model (specifically, the calculation of the specular term). While the book talks about Phong Shading, it never mentions the Phong Reflection Model when talking about specular highlights (or elsewhere at all). So I think the book isn't _wrong_, it just presents a simplified reflection model that looks very similar to Phong's.

That said, I agree with the spirit of your comment - it would be better if the book followed the Phong Reflection Model. It might be too late to change for the print version, but I'll ask!

Thanks again for bringing this up!

--Gabriel

**Comment by RichardMulder** [comment]
Your understanding is indeed correct! 

And after some more research, I agree, the term "Phong Shading" definitely does not imply "Phong Interpolation + Phong Reflection Model", so the book indeed isn't wrong.

Also, thanks for writing a wonderful, accessible book about Computer Graphics, and congratulations on getting it published!
