### ISSUE TITLE
vector OC.

### ISSUE THREAD

**Issue by UnDesSix** [ggambetta/computer-graphics-from-scratch#18]
Hi,

Firstable, thank you for this very precise tutorial.

I may be wrong because this is the first time I m doing this kind of maths, but would not be more accurate to say that **vector CO = O−C** instead of **vector OC = O−C** ? (Cf. chapter "Basic ray tracing", title "Rays meet sphere") ?

**Comment by ggambetta** [comment]
Hi, thanks for bringing this up.

Yes, I believe you're right. Will get this fixed.

--Gabriel

**Comment by ggambetta** [comment]
This has been fixed for a while now :)
