### ISSUE TITLE
When culling back faces, we can avoid calculating the center of the triangle.

### ISSUE THREAD

**Issue by YRFT** [ggambetta/computer-graphics-from-scratch#23]
https://github.com/ggambetta/computer-graphics-from-scratch/blob/4d3f72c74755cb14a2d6c03655a944b1a5060578/demos/raster-10.html#L457

As we want to optimize performance, using any triangle vertex instead of the center seems more desirable. Moreover, using a triangle vertex is more in line with [the description in the book](https://gabrielgambetta.com/computer-graphics-from-scratch/12-hidden-surface-removal.html#:~:text=Suppose%20we%20have,to%20the%20camera.) and less confusion.

---

Incidentally, if we wrote
https://github.com/ggambetta/computer-graphics-from-scratch/blob/4d3f72c74755cb14a2d6c03655a944b1a5060578/demos/raster-10.html#L458
 as `if (Dot(centre, normal) <= 0)`, it would fit [the description](https://gabrielgambetta.com/computer-graphics-from-scratch/12-hidden-surface-removal.html#:~:text=The%20classification%20criterion%20is%20simply%20this%3A) better.

**Comment by ggambetta** [comment]
This was sitting on my inbox, I think it's a good idea, just haven't gotten around to doing it. Feel free to send a PR :)

**Comment by YRFT** [comment]
OK, I got it :)

**Comment by YRFT** [comment]
I have created the pull request (https://github.com/ggambetta/computer-graphics-from-scratch/pull/28) that resolves this issue.
