### ISSUE TITLE
Incorrect calculation of directional lighting in `ComputeLighting`

### ISSUE THREAD

**Issue by linux-admin0001** [ggambetta/computer-graphics-from-scratch#26]
Hello, I noticed the wrong behavior in directional lighting.

My scene in pseudocode:
```xml
light {
    type = directional
    intensity = 1
    direction = (0, 0, 1)
}

sphere {
    center = (0, -1, 3)
    radius = 1
    color = (255, 0, 0) 
}
sphere {
    center = (2, 0, 4)
    radius = 1
    color = (0, 0, 255) 
}
sphere {
    center = (-2, 0, 4)
    radius = 1
    color = (0, 255, 0) 
}
```

I get a scene like this:
![image](https://user-images.githubusercontent.com/73735838/210248383-a157c0ac-0bc0-4e88-8ab9-c65fbac5b448.png)

**Comment by linux-admin0001** [comment]
But I get the right picture if I negate the normal
![image](https://user-images.githubusercontent.com/73735838/210248603-02c74e4e-50ff-4808-9a6b-9bd923b169d4.png)
I think this is because the normal of the sphere directed at the camera is opposite in direction to the illumination vector.
```diff
ComputeLighting(P, N) {
    i = 0.0
    for light in scene.Lights {
        if light.type == ambient {
            i += light.intensity
        } else {
            if light.type == point {
                L = light.position - P
            } else {
-                L = light.direction
+               L = -light.direction
            }
            n_dot_l = dot(N, L)
                if n_dot_l > 0 {
                i += light.intensity * n_dot_l/(length(N) * length(L))
            }
        }
    }
    return i
}
```
This does not happen with point lighting, since the vector L is directed in the same direction as the normal

**Comment by ggambetta** [comment]
I'm on holidays, will take a look in a week. But (0, 0, 0) is not a valid
direction vector, I'm surprised anything works at all, it should cause a
division by zero among other things.

**Comment by linux-admin0001** [comment]
there is not (0,0,0), but (0,0,1), I made a typo when I wrote the issue

**Comment by linux-admin0001** [comment]
by the way, have a nice holidays!

**Comment by ggambetta** [comment]
Took a look at this. By convention the book defines the vector L as going
*to* the light. This works fine as you pointed out for point lights.

It also works fine for directional lights as it is; it's the direction of
the light in your test data that you need to invert.

The relevant section in the book (
https://gabrielgambetta.com/computer-graphics-from-scratch/03-light.html#directional-lights)
says "*You can think of them as infinitely distant point lights located in
the specified direction.*"
