### ISSUE TITLE
A minor math mistake

### ISSUE THREAD

**Issue by KrisYu** [ggambetta/computer-graphics-from-scratch#4]
In the Basic ray tracing chapter.

> In general, using a 60 FOV in the horizontal and vertical directions produces reasonable images; this is achieved with Vw = Vh = d = 1.

here if the FOV is 60, d should not equal 1. draw the triangle. 

<img width="320" alt="Screen Shot 2019-03-13 at 3 50 48 PM" src="https://user-images.githubusercontent.com/2805466/54261885-dc562980-45a7-11e9-93e8-62d3a377bb24.png">

 
A great book, thanks for sharing.

**Comment by spectrumgomas** [comment]
I'd let Vw=Vh=d=1 for the sake of simplicity and I would clarify so FOV is approximately 53º

**Comment by ggambetta** [comment]
Went with @spectrumgomas's suggestion. Thanks for reporting, @KrisYu!
