### ISSUE TITLE
Can you provide an epub version?

### ISSUE THREAD

**Issue by NightMachinery** [ggambetta/computer-graphics-from-scratch#5]
I read much better in an e-reader than on screens.

**Comment by waqarsaleem** [comment]
According to [this tutorial](https://medium.com/@sebahaeusler/how-to-epub-from-markdown-188fef880fbb), you can use [pandoc](https://pandoc.org/epub.html) for the conversion.

**Comment by Jimmy-Z** [comment]
If you're using Kindle, I'm just using the Send to Kindle Chrome extension, works exceptionally well for this, and every other web articles I tried it on.

**Comment by ggambetta** [comment]
You can get an ePub version from No Starch Press: https://nostarch.com/computer-graphics-scratch
