### ISSUE TITLE
Comparing distance and radius

### ISSUE THREAD

**Issue by Gr1dlock** [ggambetta/computer-graphics-from-scratch#9]
https://github.com/ggambetta/computer-graphics-from-scratch/blob/1bb5ac8c46ede34d56017110b2ae51fa1fe4546a/demos/raster-10.html#L521
You computate unnormalized distance and compare it with square radius. For example, let's take surface Z - 1 = 0 and circle (0, 0, 1 + sqrt(3)) with raadius sqrt(3). Distance from the surface to the circle's center is sqrt(3) and program should detect that there is an intersection, but you compare it not whith radius(sqrt(3)) but with square radius(3).
![image](https://user-images.githubusercontent.com/48106069/62698063-e8bea100-b9e4-11e9-99a8-e04d963eab5d.png)

**Comment by ggambetta** [comment]
Hi Dmitriy, thanks for your message.

Good catch! Here's a PR to fix it:
https://github.com/ggambetta/computer-graphics-from-scratch/pull/10 Mind
taking a look?

Thanks,

--Gabriel
